#!/usr/bin/env python
"""A simple plotting tool to create spectral diagnostics plots similar to those
originally proposed by M. Kromer (see, for example, Kromer et al. 2013, figure
4).
"""
import logging
import numpy as np
import astropy.units as units
import astropy.constants as csts
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.lines as line
import matplotlib.cm as cm
import pandas as pd

logger = logging.getLogger(__name__)

elements = {'neut': 0, 'h': 1, 'he': 2, 'li': 3, 'be': 4, 'b': 5, 'c': 6, 'n':
            7, 'o': 8, 'f': 9, 'ne': 10, 'na': 11, 'mg': 12, 'al': 13, 'si':
            14, 'p': 15, 's': 16, 'cl': 17, 'ar': 18, 'k': 19,    'ca': 20,
            'sc': 21, 'ti': 22, 'v': 23, 'cr': 24, 'mn': 25, 'fe': 26, 'co':
            27, 'ni': 28, 'cu': 29, 'zn': 30, 'ga': 31, 'ge': 32, 'as': 33,
            'se': 34, 'br': 35, 'kr': 36, 'rb': 37, 'sr': 38, 'y': 39,  'zr':
            40, 'nb': 41, 'mo': 42, 'tc': 43, 'ru': 44, 'rh': 45, 'pd': 46,
            'ag': 47, 'cd': 48}
inv_elements = dict([(v, k) for k, v in elements.items()])


class tardis_kromer_plotter(object):
    """A plotter, generating spectral diagnostics plots as proposed by M.
    Kromer.

    With this tool, a specific visualisation of Tardis spectra may be produced.
    It illustrates which elements predominantly contribute to the emission and
    absorption part of the emergent (virtual) packet spectrum.

    Once a model is defined, a series of queries is performed on the packet
    property arrays. The results are cached and the "Kromer" plot is produced
    with the main method of this class, namely with ~generate_plot.

    Parameters
    ----------
    mdl : minimal_model
        a minimal_model object containing the Tardis run
    mode : str, optional
        'real' (default) or 'virtual'; determines which packet population is
        used to generate the Kromer plot.

    Notes
    -----
    For this to work, the model must be generated by a Tardis calculation using
    the virtual packet logging capability. This requires a compilation with the
    --with-vpacket-logging flag.

    This way of illustrating the spectral synthesis process was introduced by
    M. Kromer (see e.g. [1]_).

    References
    ----------

    .. [1] Kromer et al. "SN 2010lp - Type Ia Supernova from a Violent Merger
       of Two Carbon-Oxygen White Dwarfs" ApjL, 2013, 778, L18

    """
    def __init__(self, mdl, lines, mode="real"):

        self._mode = None
        self.mode = mode

        self._mdl = None
        self._zmax = 32
        self._cmap = cm.jet
        self._xlim = None
        self._ylim = None
        self._twinx = False

        self._bins = None
        self._ax = None
        self._pax = None

        self._esc_mask = None
        self._noint_mask = None
        self._escat_mask = None
        self._escatonly_mask = None
        self._line_mask = None
        self._lam_escat = None
        self._lam_noint = None
        self._weights_escat = None
        self._weights_noint = None
        self._line_in_infos = None
        self._line_in_nu = None
        self._line_in_L = None
        self._line_out_infos = None
        self._line_out_nu = None
        self._line_out_L = None


        self._last_interaction_type = None
        self._last_line_interaction_in_id = None
        self._last_line_interaction_out_id = None
        self._last_interaction_in_nu = None
        self._output_nu = None
        self._packet_luminosity = None

        self.mdl = pd.HDFStore(mdl)
        self.lines = pd.HDFStore(lines)

    @property
    def mode(self):
        """packet mode - use real or virtual packets for plotting"""
        return self._mode

    @mode.setter
    def mode(self, val):
        known_modes = ["real", "virtual"]
        try:
            assert(val in known_modes)
        except AssertionError:
            raise ValueError("unknown mode")
        self._mode = val

    @property
    def zmax(self):
        """Maximum atomic number"""
        return self._zmax

    @property
    def cmap(self):
        """Colour map, used to highlight the different atoms"""
        return self._cmap

    @property
    def ax(self):
        """Main axes, containing the emission part of the Kromer plot"""
        return self._ax

    @property
    def pax(self):
        """Secondary axes, containing the absorption part of the Kromer plot"""
        return self._pax

    @property
    def bins(self):
        """frequency binning for the spectral visualisation"""
        return self._bins

    @property
    def xlim(self):
        """wavelength limits"""
        return self._xlim

    @property
    def ylim(self):
        """Flux limits"""
        return self._ylim

    @property
    def twinx(self):
        """switch to decide where to place the absorption part of the Kromer
        plot"""
        return self._twinx

    @property
    def esc_mask(self):
        """Masking array, highlighting the packets that have positive energy"""
        if self._esc_mask is None:
            self._esc_mask = \
                self.mdl.get_node("runner").output_energy.values.read() >= 0

        return self._esc_mask

    @property
    def last_interaction_type(self):
        """Highlighting only the packets with positive energy"""
        if self._last_interaction_type is None:
            self._last_interaction_type = \
                    self.mdl.get_node("runner").last_interaction_type.values.read()[self.esc_mask]
        return self._last_interaction_type

    @property
    def last_line_interaction_in_id(self):
        """Highlighting only the packets with positive energy"""
        if self._last_line_interaction_in_id is None:
            self._last_line_interaction_in_id = \
                    self.mdl.get_node("runner").last_line_interaction_in_id.values.read()[self.esc_mask]
        return self._last_line_interaction_in_id

    @property
    def last_line_interaction_out_id(self):
        """Highlighting only the packets with positive energy"""
        if self._last_line_interaction_out_id is None:
            self._last_line_interaction_out_id = \
                    self.mdl.get_node("runner").last_line_interaction_out_id.values.read()[self.esc_mask]
        return self._last_line_interaction_out_id

    @property
    def last_interaction_in_nu(self):
        """Highlighting only the packets with positive energy"""
        if self._last_interaction_in_nu is None:
            self._last_interaction_in_nu = \
                    self.mdl.get_node("runner").last_interaction_in_nu.values.read()[self.esc_mask]
        return self._last_interaction_in_nu

    @property
    def output_nu(self):
        """Highlighting only the packets with positive energy"""
        if self._output_nu is None:
            self._output_nu = \
                    self.mdl.get_node("runner").output_nu.values.read()[self.esc_mask]
        return self._output_nu

    @property
    def packet_luminosity(self):
        """Highlighting only the packets with positive energy"""
        if self._packet_luminosity is None:
            self._packet_luminosity = \
                    self.mdl.get_node("runner").packet_luminosity.values.read()[self.esc_mask]
        return self._packet_luminosity

    @property
    def noint_mask(self):
        """Masking array, highlighting the packets that never interacted"""
        if self._noint_mask is None:
            self._noint_mask = \
                    self.last_interaction_type == -1
        return self._noint_mask

    @property
    def escat_mask(self):
        """Masking array, highlighting the packets that performed Thomson
        scatterings"""
        if self._escat_mask is None:
            self._escat_mask = \
                self.last_interaction_type == 1
        return self._escat_mask

    @property
    def escatonly_mask(self):
        """Masking array, highlighting the packets that only performed Thomson
        scatterings"""
        if self._escatonly_mask is None:
            tmp = ((self.last_line_interaction_in_id == -1) *
                   (self.escat_mask)).astype(np.bool)
            self._escatonly_mask = tmp
        return self._escatonly_mask

    @property
    def line_mask(self):
        """Mask array, highlighting packets whose last interaction was with a
        line"""
        if self._line_mask is None:
            self._line_mask = \
                ((self.last_interaction_type > -1) *
                 (self.last_line_interaction_in_id > -1))
        return self._line_mask

    @property
    def lam_noint(self):
        """Wavelength of the non-interacting packets"""
        if self._lam_noint is None:
            self._lam_noint = \
                (csts.c.cgs /
                 (self.output_nu[self.noint_mask]*units.Hz)).to(units.AA)
        return self._lam_noint

    @property
    def lam_escat(self):
        """Wavelength of the purely electron scattering packets"""
        if self._lam_escat is None:
            self._lam_escat = \
                (csts.c.cgs /
                 (self.output_nu[self.escatonly_mask]*units.Hz)).to(units.AA)
        return self._lam_escat

    @property
    def weights_escat(self):
        """luminosity of the only electron scattering packets"""
        if self._weights_escat is None:
            self._weights_escat = self.packet_luminosity[self.escatonly_mask]
        return self._weights_escat

    @property
    def weights_noint(self):
        """luminosity of the non-interacting packets"""
        if self._weights_noint is None:
            self._weights_noint = self.packet_luminosity[self.noint_mask]
        return self._weights_noint

    @property
    def line_out_infos(self):
        """Line ids of the transitions packets were emitted last"""
        if self._line_out_infos is None:
            tmp = self.last_line_interaction_out_id
            ids = tmp[self.line_mask]
            self._line_out_infos = self.lines.lines.iloc[ids]
 #           print self._line_out_infos.atomic_number.values
            return self._line_out_infos

    @property
    def line_out_nu(self):
        """frequency of the transitions packets were emitted last"""
        if self._line_out_nu is None:
            self._line_out_nu = self.output_nu[self.line_mask]*units.Hz
        return self._line_out_nu

    @property
    def line_out_L(self):
        """luminosity of the line interaction packets"""
        if self._line_out_L is None:
#            tmp = self.packet_luminosity
            self._line_out_L = self.packet_luminosity[self.line_mask]
        return self._line_out_L

    @property
    def line_in_infos(self):
        """Line ids of the transitions packets were last absorbed"""
        if self._line_in_infos is None:
#           tmp = self.last_line_interaction_in_id
            ids = self.last_line_interaction_in_id[self.line_mask]
            self._line_in_infos = self.lines.lines.iloc[ids]
        return self._line_in_infos

    @property
    def line_in_nu(self):
        """frequencies of the transitions packets were last absorbed"""
        if self._line_in_nu is None:
            nus = self.last_interaction_in_nu*units.Hz
            self._line_in_nu = nus[self.line_mask]
        return self._line_in_nu

    @property
    def line_in_L(self):
        """luminosity of the line interaction packets"""
        if self._line_in_L is None:
            self._line_in_L = self.packet_luminosity[self.line_mask]
        return self._line_in_L

    def _reset_cache(self):
        """Reset cached variables - only needed in case the model is changed
        after initialisation"""

        self._noint_mask = None
        self._escat_mask = None
        self._escatonly_mask = None
        self._line_mask = None
        self._lam_escat = None
        self._lam_noint = None
        self._weights_escat = None
        self._weights_noint = None
        self._line_in_infos = None
        self._line_in_nu = None
        self._line_in_L = None
        self._line_out_infos = None
        self._line_out_nu = None
        self._line_out_L = None

        self._last_interaction_type = None
        self._last_line_interaction_in_id = None
        self._last_line_interaction_out_id = None
        self._last_interaction_in_nu = None
        self._output_nu = None
        self._packet_luminosity = None

    def generate_plot(self, ax=None, cmap=cm.jet, bins=None, xlim=None,
                      ylim=None, twinx=False):
        """Generate the actual "Kromer" plot

        Parameters
        ----------
        ax : matplotlib.axes or None
            axes object into which the emission part of the Kromer plot should
            be plotted; if None, a new one is generated (default None)
        cmap : matplotlib.cm.ListedColormap or None
            color map object used for the illustration of the different atomic
            contributions (default matplotlib.cm.jet)
        bins : np.ndarray or None
            array of the wavelength bins used for the illustration of the
            atomic contributions; if None, the same binning as for the stored
            virtual spectrum is used (default None)
        xlim : tuple or array-like or None
            wavelength limits for the display; if None, the x-axis is
            automatically scaled (default None)
        ylim : tuple or array-like or None
            flux limits for the display; if None, the y-axis is automatically
            scaled (default None)
        twinx : boolean
            determines where the absorption part of the Kromer plot is placed,
            if True, the absorption part is attached at the top of the main
            axes box, otherwise it is placed below the emission part (default
            False)

        Returns
        -------
        fig : matplotlib.figure
            figure instance containing the plot
        """
        self._ax = None
        self._pax = None

        self._cmap = cmap
        self._ax = ax
        self._xlim = xlim
        self._ylim = ylim
        self._twinx = twinx

        if bins is None:
            self._bins = (self.mdl.get_node("runner").spectrum.wavelength.values.read()[::-1] * units.cm).to("AA")
        else:
            self._bins = bins
        self._axes_handling_preparation()
        self._generate_emission_part()
        self._generate_and_add_colormap()
        self._generate_and_add_legend()
        self._paxes_handling_preparation()
        self._generate_absorption_part()
        self._axis_handling_label_rescale()

        return plt.gcf()

    def _axes_handling_preparation(self):
        """prepare the main axes; create a new axes if none exists"""

        if self._ax is None:
            self._ax = plt.figure().add_subplot(111)

    def _paxes_handling_preparation(self):
        """prepare the axes for the absorption part of the Kromer plot
        according to the twinx value"""

        self._pax = self._ax.twinx() if self.twinx else self._ax

    def _generate_emission_part(self):
        """generate the emission part of the Kromer plot"""

        lams = [self.lam_noint, self.lam_escat]
        weights = [self.weights_noint, self.weights_escat]
        colors = ["black", "grey"]

        mas = self.line_out_infos
        for zi in xrange(1, self.zmax+1):
            mask = mas.atomic_number.values == zi
            lams.append((csts.c.cgs / (self.line_out_nu[mask])).to(units.AA))
            weights.append(self.line_out_L[mask])
            colors.append(self.cmap(float(zi) / float(self.zmax)))

        Lnorm = sum(np.sum(w) for w in weights)
        ret = self.ax.hist(lams, bins=self.bins, stacked=True,
                 histtype="stepfilled", normed=True, weights=weights)

        for i, col in enumerate(ret[-1]):
            for reti in col:
                reti.set_facecolor(colors[i])
                reti.set_edgecolor(colors[i])
                reti.set_linewidth(0)
                reti.xy[:, 1] *= Lnorm

        self.ax.plot((self.mdl.get_node("runner").spectrum.wavelength.values.read() * units.cm).to("AA"), (self.mdl.get_node("runner").spectrum.luminosity_density_lambda.values.read() * units.erg / units.s / units.cm).to("erg / s / AA"), color="blue", drawstyle="steps-post", lw=0.5)

    def _generate_absorption_part(self):
        """generate the absorption part of the Kromer plot"""

        lams = []
        weights = []
        colors = []

        mas = self.line_in_infos
        for zi in xrange(1, self.zmax+1):
            mask = (mas.atomic_number == zi).values
            lams.append((csts.c.cgs / self.line_in_nu[mask]).to(units.AA))
            weights.append(self.line_in_L[mask])
            colors.append(self.cmap(float(zi) / float(self.zmax)))

        Lnorm = 0 - sum(np.sum(w) for w in weights)
        ret = self.pax.hist(lams, bins=self.bins, stacked = True,
                            histtype = "stepfilled", normed=True,
                            weights = weights)

        for i, col in enumerate(ret[-1]):
            for reti in col:
                reti.set_facecolor(colors[i])
                reti.set_edgecolor(colors[i])
                reti.set_linewidth(0)
                reti.xy[:, 1] *= Lnorm

    def _generate_and_add_colormap(self):
        """generate the custom color map, linking colours with atomic
        numbers"""

        values = [self.cmap(float(i) / float(self.zmax))
                  for i in xrange(1, self.zmax+1)]

        custcmap = matplotlib.colors.ListedColormap(values)
        bounds = np.arange(self.zmax+1) + 0.5
        norm = matplotlib.colors.Normalize(vmin=1, vmax=self.zmax+1)
        mappable = cm.ScalarMappable(norm=norm, cmap=custcmap)
        mappable.set_array(np.linspace(1, self.zmax + 1, 256))
        labels = [inv_elements[zi].capitalize()
                  for zi in xrange(1, self.zmax+1)]

        mainax = self.ax
        cbar = plt.colorbar(mappable, ax=mainax)
        cbar.set_ticks(bounds)
        cbar.set_ticklabels(labels)

    def _generate_and_add_legend(self):
        """add legend"""

        bpatch = patches.Patch(color="black", label="photosphere")
        gpatch = patches.Patch(color="grey", label="e-scattering")
        bline = line.Line2D([], [], color="blue", label="virtual spectrum")
        self.ax.legend(handles=[bline, gpatch, bpatch])

    def _axis_handling_label_rescale(self):
        """add axis labels and perform axis scaling"""

        if self.ylim is None:
            self.ax.autoscale(axis="y")
        else:
            self.ax.set_ylim(self.ylim)

        self._ylim = self.ax.get_ylim()

        if self.xlim is None:
            self.ax.autoscale(axis="x")
        else:
            self.ax.set_xlim(self.xlim)

        self._xlim = self.ax.get_xlim()

        if self.twinx:
            self.pax.set_ylim([-self.ylim[-1], -self.ylim[0]])
            self.pax.set_yticklabels([])
        else:
            self.pax.set_ylim([-self.ylim[-1], self.ylim[-1]])
        self.pax.set_xlim(self.xlim)

        self.ax.set_xlabel(r"$\lambda$ [$\mathrm{\AA}$]")
        ylabel = r"$L_{\mathrm{\lambda}}$ [$\mathrm{erg\,s^{-1}\,\AA^{-1}}$]"
        self.ax.set_ylabel(ylabel)


if __name__ == "__main__":

    kromer_plot = tardis_kromer_plotter(mdl = "model_00113_3.h5", lines = "lines_00113_3.h5")
    kromer_plot.generate_plot(twinx = True, ylim = [0, 7e39])
    plt.show()
